### ISSUE TITLE
Network Error - no more information...

### ISSUE THREAD

**Issue by borrougagnou** [sikelio/plexmanager#77]
Hello,

I have a problem, I have a Plex Server on my NAS
(HTTPS only).

and I obtain the following error:
"Network Error - Please Check your network connection and try again"

I tried with my private IP, and also with my public IP (visible in Plex>Settings>Hostname>Settings>Remote Access)

But nothing work, I have always the same message, I also switched http/https/computer/nas

But nothing change...

It work without problem on my web browser.

my version on the server: 1.29.2.6364 
my version on the web plex:  4.106.1 

Regards.

**Comment by sikelio** [comment]
Hi, I will make some tests with your Plex version.
I have some questions for you.
Have you checked if the port of Plex is 32400 or something else ? And then have you checked if the port used by Plex is opened on your NAS ? It could maybe help. I will on my side try to understand where the problem could be.
It's possible that your problem is already fixed in dev branch and will be fixed with version 0.0.2-beta

**Comment by borrougagnou** [comment]
Hello,
thank you for your answer,
the port of plex is 32400 yes,
I access to plex using my web browser,
I enter the IP address of my NAS followed by the port (32400)
then plex open, and ask me my login and password

Also, my NAS can't be opened from outside, it mean I need to be at home if I want to access on my NAS.


Maybe about the 0.0.2-beta but there is no release on izzy or f-droid atm, same on beta part, any idea when it will come out ?

**Comment by sikelio** [comment]
Hello,
This feature will probably be added in a quite long time because if I have to support older version of Plex right now, I will not have time for other necessary functionality. It could be possible that one day I'll create an app for older version.
